### ISSUE TITLE
Wrapper#upload_execution_attachment broken in TL API

### ISSUE THREAD

**Issue by turboladen** [turboladen/test_linker#6]
`#uploadExecutionAttachment` is broken due to a really, really dumb error in
the 1.9.1 testlink API:

```
'tl.uploadExecutionAttachment' => 'this::uploadExecutionAttachment',
```

Should be:

```
'tl.uploadExecutionAttachment' => 'this:uploadExecutionAttachment',
```

(Thanks to fishstick for this bug via email!)

**Comment by turboladen** [comment]
I'm not sure if there's anything I can do over here about it, but I'll certainly look in to it!

**Comment by fishstick** [comment]
It's not, I had to manually edit the remote XMLRPC.class.php to fix it. It wasn't listed on their Mantis tracker yet either, so it probably won't be fixed for a while.

**Comment by turboladen** [comment]
That’s lame sauce.  Ok, I’ll probably close this then.

On May 15, 2011, at 11:36 PM, fishstick wrote:

> It's not, I had to manually edit the remote XMLRPC.class.php to fix it. It wasn't listed on their Mantis tracker yet either, so it probably won't be fixed for a while.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/turboladen/test_linker/issues/6#comment_1171803

---

This email has been scanned by the MessageLabs Email Security System.
For more information please visit http://www.messagelabs.com/email 

---

**Comment by turboladen** [comment]
Nothing to fix here on our end.
